### ISSUE TITLE
Persona Template

### ISSUE THREAD

**Issue by lapinell** [nashvillefcc/personal-job-portal#1]
Goal: Create a template for our user personas

Tools:
   - Illustrator (svgs, pngs)
   - InDesign (.idd -> .pdf) 

Resources:
   - [Hypothesized Personas](https://docs.google.com/document/d/1jrad_XGJn-nwlGbDfhV2WnwvsWSpAHLE2VeIbXqMHgE/edit) to base template on 
   - [Style Guide]() To be uploaded
   - [Example Persona templates](https://duckduckgo.com/?q=persona+templates&atb=v152-5__&iax=images&ia=images)

**Comment by kooorczu** [comment]
Hey,
I prepared template, check it out and let me know what you think
[Persona template.pdf](https://github.com/nashvillefcc/personal-job-portal/files/2984768/Persona.template.pdf)

**Comment by lapinell** [comment]
This looks amazing! Thanks!
